name: Codesign apple binaries with Apple Developer certificate
description: |
  Uses Apple provided developer certificate to codesign binaries for execution in the OS.
author: hjpotter92

inputs:
  developer-certificate-id:
    description: Apple provided certificate ID
    required: true
  developer-certificate-base64:
    description: Base64 encoded developer certificate
    required: true
  developer-certificate-password:
    description: Password needed to import the certificate
    required: true
  binary-path:
    required: true
    description: Path where binaries which need to be codesigned are stored/available
  keychain-password:
    description: Optional password for setting up keychain
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Generate keychain
      id: keychain
      shell: bash
      run: ${{ github.action_path }}/scripts/keychain.bash
      env:
        KEYCHAIN_PASSWORD: ${{ inputs.keychain-password }}
        DEVELOPER_CERTIFICATE_BASE64: ${{ inputs.developer-certificate-base64 }}

    - name: Sign binaries
      id: codesign
      shell: bash
      run: ${{ github.action_path }}/scripts/codesign.bash
      env:
        PASSWORD: ${{ steps.keychain.outputs.password }}
        KEYCHAIN_FILE: ${{ steps.keychain.outputs.keychain-file }}
        CERTIFICATE_FILE: ${{ steps.keychain.outputs.certificate-file }}
        BINARY_PATH: ${{ inputs.binary-path }}
        DEVELOPER_CERIFICATE_ID: ${{ inputs.developer-certificate-id }}
        DEVELOPER_CERTIFICATE_PASSWORD: ${{ inputs.developer-certificate-password }}
