name: Codesign apple binaries with Apple Developer certificate
description: >-
  Uses Apple provided developer certificate to codesign binaries for
  execution in the OS. Also notarizes the files through `notarytool`
author: hjpotter92

inputs:
  developer-certificate-id:
    description: Apple provided certificate ID
    required: true
  developer-certificate-base64:
    description: Base64 encoded developer certificate
    required: true
  developer-certificate-password:
    description: Password needed to import the certificate
    required: true
  app-notarization-team-id:
    required: true
    description: Developer team ID
  app-notarization-email:
    required: true
    description: Developer Apple email ID
  app-notarization-password:
    required: true
    description: App-specific password for your Apple ID.
  binary-path:
    required: true
    description: Path where binaries which need to be codesigned are stored/available
  keychain-password:
    description: Optional password for setting up keychain
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Fail if run on non-macOS runner
      if: ${{ runner.os != 'macOS' }}
      shell: bash
      run: |
        echo "Failed to run action on ${{ runner.os }}. Requires macos runner"
        exit 1

    # - name: Exit with no-op until developer licence gets renewed!
    #   if: ${{ runner.os == 'macOS' }}
    #   shell: bash
    #   run: |
    #     echo "bypassing codesigning step"

    - name: Generate keychain, codesign binaries and notarize package
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: ${{ github.action_path }}/scripts/apple-codesign.bash
      env:
        KEYCHAIN_PASSWORD: ${{ inputs.keychain-password }}
        DEVELOPER_CERTIFICATE_BASE64: ${{ inputs.developer-certificate-base64 }}
        BINARY_PATH: ${{ inputs.binary-path }}
        DEVELOPER_CERTIFICATE_ID: ${{ inputs.developer-certificate-id }}
        DEVELOPER_CERTIFICATE_PASSWORD: ${{ inputs.developer-certificate-password }}
        NOTARIZATION_TEAM_ID: ${{ inputs.app-notarization-team-id }}
        NOTARIZATION_EMAIL: ${{ inputs.app-notarization-email }}
        NOTARIZATION_PASSWORD: ${{ inputs.app-notarization-password }}
